[project]
name = "github-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.5.0",
]

[project.scripts]
github-cli = "github_cli.main:main"
